#student details
a=input("enter student name:")
b=int(input("enter student USN: "))
c=input("enter student course:")
d=input("enter your college name:")
#print(STUDENT DETAILS)
print("student name:",a)
print("student USN",b)
print("student course",c)
print("college name:",d)